# Generated by Django 5.2 on 2025-04-08 09:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('sanandaj', 'sanandaj'), ('tehran', 'tehran'), ('shiraz', 'shiraz'), ('boukan', 'boukan')], max_length=50)),
                ('brand', models.CharField(choices=[('peugeot', 'peugeot'), ('renault', 'renault'), ('iran khodro', 'iran khodro'), ('saipa', 'saipa')], max_length=100)),
                ('model', models.CharField(choices=[('206', '206'), ('405', '405'), ('pars', 'pars'), ('l90', 'l90'), ('sandro', 'sandro'), ('duster', 'duster'), ('samand', 'samand'), ('dena', 'dena'), ('tara', 'tara'), ('shahin', 'shahin'), ('tiba', 'tiba'), ('saina', 'saina')], max_length=50)),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('fuel_type', models.CharField(choices=[('gsoline', 'gasoline'), ('corporate dual fuel', 'corporate dual fuel'), ('manual dual fuel', 'manual dual fuel'), ('diesel', 'diesel')], max_length=50)),
                ('production_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2001), django.core.validators.MaxValueValidator(2025)])),
                ('color', models.CharField(choices=[('white', 'white'), ('black', 'black'), ('gray', 'gray'), ('blue', 'blue')], max_length=50)),
                ('body_condition', models.CharField(choices=[('intact', 'intact'), ('minor scratches', 'minor scratches'), ('polished unpainted', 'polished unpainted'), ('partially painted', 'partially painted'), ('mostly painted', 'mostly painted'), ('fully painted', 'fully painted'), ('crashed', 'crashed'), ('scrapped', 'scrapped')], max_length=50)),
                ('front_chassis_condition', models.CharField(choices=[('intact', 'intact'), ('damaged', 'damaged'), ('painted', 'painted')], max_length=50)),
                ('rear_chassis_condition', models.CharField(choices=[('intact', 'intact'), ('damaged', 'damaged'), ('painted', 'painted')], max_length=50)),
                ('engine_condition', models.CharField(choices=[('intact', 'intact'), ('needs repair', 'needs repair'), ('replaced', 'replaced')], max_length=50)),
                ('gearbox', models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic')], max_length=20)),
                ('third_party_insurance_period', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('price', models.IntegerField()),
                ('willing_to_exchange', models.BooleanField()),
                ('description', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 09xxxxxxxxx', regex='^09\\d{9}$')])),
                ('ad_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MotorcycleAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('sanandaj', 'sanandaj'), ('tehran', 'tehran'), ('shiraz', 'shiraz'), ('boukan', 'boukan')], max_length=50)),
                ('brand', models.CharField(choices=[('apache', 'apache'), ('yamaha', 'yamaha'), ('honda', 'honda')], max_length=100)),
                ('model', models.CharField(choices=[('a 160', 'a 160'), ('a 180', 'a 180'), ('a 200', 'a 200'), ('yt 125', 'yt 125'), ('yt 250', 'yt 250'), ('yt 400', 'yt 400'), ('hcb 150', 'hcb 150'), ('hcb 250', 'hcb 250'), ('hcb 300', 'hcb 300')], max_length=50)),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('production_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2001), django.core.validators.MaxValueValidator(2025)])),
                ('price', models.IntegerField()),
                ('willing_to_exchange', models.BooleanField()),
                ('description', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 09xxxxxxxxx', regex='^09\\d{9}$')])),
                ('ad_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
