# Generated by Django 5.2 on 2025-04-13 07:03

from django.db import migrations, models
import datetime

def set_default_created_updated(apps, schema_editor):
    MotorcycleAd = apps.get_model('ads_app', 'MotorcycleAd')
    for motorcycle_ad in MotorcycleAd.objects.all():
        motorcycle_ad.created = datetime.datetime.now()
        motorcycle_ad.updated = datetime.datetime.now()
        motorcycle_ad.save()
    

def undo_set_default_created_updated(apps, schema_editor):
    MotorcycleAd = apps.get_model('ads_app', 'MotorcycleAd')
    for motorcycle_ad in MotorcycleAd.objects.all():
        motorcycle_ad.created = None
        motorcycle_ad.updated = None
        motorcycle_ad.save()




class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0004_alter_carad_created_alter_carad_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='MotorcycleAd',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, default=None)),
            migrations.AddField(
                model_name='MotorcycleAd',
                name='updated',
                field=models.DateTimeField(auto_now=True, null=True, default=None)),
                migrations.RunPython(code=set_default_created_updated, reverse_code=undo_set_default_created_updated)
    ]
