# Generated by Django 5.2 on 2025-04-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0006_alter_motorcyclead_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='motorcyclead',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='motorcyclead',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
