# Generated by Django 5.2 on 2025-04-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0009_motorcyclead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending'),
        ),
    ]
