# Generated by Django 5.2 on 2025-04-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0010_alter_carad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcyclead',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending'),
        ),
    ]
