# Generated by Django 5.2 on 2025-04-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0013_carad_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carad',
            name='image',
        ),
    ]
