# Generated by Django 5.2 on 2025-04-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0017_caradimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caradimage',
            name='description',
        ),
    ]
