# Generated by Django 5.2 on 2025-04-25 10:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('family_name', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 09xxxxxxxxx', regex='^09\\d{9}$')])),
                ('date_of_birth', models.DateField(blank=True)),
                ('bio', models.TextField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
