# Generated by Django 5.2 on 2025-04-12 09:53

from django.db import migrations, models
import datetime

def set_default_created_updated(apps, schema_editor):
    CarAd = apps.get_model('ads_app', 'CarAd')
    for car_ad in CarAd.objects.all():
        car_ad.created = datetime.datetime.now()
        car_ad.updated = datetime.datetime.now()
        car_ad.save()


def undo_set_default_created_updated(apps, schema_editor):
    CarAd = apps.get_model('ads_app', 'CarAd')
    for car_ad in CarAd.objects.all():
        car_ad.created = None
        car_ad.updated = None
        car_ad.save()



class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='CarAd',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, default=None)
            ),
        migrations.AddField(
            model_name='CarAd',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, default=None)
            ),
        migrations.RunPython(code=set_default_created_updated, reverse_code=undo_set_default_created_updated)
    ]
