# Generated by Django 5.2 on 2025-04-14 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0015_caradimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarAdImage',
        ),
    ]
