# Generated by Django 5.2 on 2025-04-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0007_alter_carad_created_alter_carad_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carad',
            name='status',
            field=models.CharField(default='pending'),
        ),
    ]
