# Generated by Django 5.2 on 2025-04-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0008_carad_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcyclead',
            name='status',
            field=models.CharField(default='pending'),
        ),
    ]
