# Generated by Django 5.2 on 2025-04-14 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0014_remove_carad_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='car_images')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending')),
                ('car_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads_app.carad')),
            ],
        ),
    ]
