# Generated by Django 5.2 on 2025-04-19 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0018_remove_caradimage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleAdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='motorcycle_images/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending')),
                ('motorcycle_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads_app.motorcyclead')),
            ],
        ),
    ]
