# Generated by Django 5.2 on 2025-04-25 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0019_motorcycleadimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='ad_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motorcyclead',
            name='ad_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycle_ads', to=settings.AUTH_USER_MODEL),
        ),
    ]
